import xml.etree.ElementTree as ET
from datetime import datetime
import os
import sys

def update_podcast_feed(title, mp3_filename, description):
    feed_file = 'feed.xml'
    # Base URL for GitHub Pages
    base_url = "https://mommocmoc.github.io/supercow-ai-news-podcast/audio/"
    mp3_url = base_url + mp3_filename
    
    # Register namespaces for iTunes tags
    ET.register_namespace('itunes', "http://www.itunes.com/dtds/podcast-1.0.dtd")
    
    if not os.path.exists(feed_file):
        rss = ET.Element('rss', version='2.0')
        rss.set('xmlns:itunes', "http://www.itunes.com/dtds/podcast-1.0.dtd")
        channel = ET.SubElement(rss, 'channel')
        ET.SubElement(channel, 'title').text = 'SuperCow AI News Podcast'
        ET.SubElement(channel, 'link').text = 'https://mommocmoc.github.io/supercow-ai-news-podcast'
        ET.SubElement(channel, 'description').text = 'Daily AI news generated by NotebookLM'
        ET.SubElement(channel, 'language').text = 'ko-KR'
    else:
        tree = ET.parse(feed_file)
        rss = tree.getroot()
        channel = rss.find('channel')

    # Add new episode
    item = ET.SubElement(channel, 'item')
    ET.SubElement(item, 'title').text = title
    # Note: length '0' is usually fine for podcasts, but real length in bytes is better
    file_size = os.path.getsize(os.path.join('audio', mp3_filename)) if os.path.exists(os.path.join('audio', mp3_filename)) else 0
    ET.SubElement(item, 'enclosure', url=mp3_url, type='audio/mpeg', length=str(file_size))
    ET.SubElement(item, 'pubDate').text = datetime.now().strftime("%a, %d %b %Y %H:%M:%S GMT")
    ET.SubElement(item, 'description').text = description
    ET.SubElement(item, '{http://www.itunes.com/dtds/podcast-1.0.dtd}summary').text = description

    # Save file
    ET.indent(rss, space='  ', level=0)
    ET.ElementTree(rss).write(feed_file, encoding='UTF-8', xml_declaration=True)
    print(f"Updated {feed_file} with {mp3_filename}")

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: python update_feed.py <title> <mp3_filename> <description>")
    else:
        update_podcast_feed(sys.argv[1], sys.argv[2], sys.argv[3])
