import xml.etree.ElementTree as ET
from datetime import datetime, timezone, timedelta
import os
import sys

def update_podcast_feed(title, audio_filename, description):
    feed_file = "feed.xml"
    base_url = "https://mommocmoc.github.io/supercow-ai-news-podcast/"
    audio_url = base_url + "audio/" + audio_filename
    image_url = base_url + "cover.png"
    
    ITUNES_NS = "http://www.itunes.com/dtds/podcast-1.0.dtd"
    ET.register_namespace("itunes", ITUNES_NS)
    
    if not os.path.exists(feed_file):
        rss = ET.Element("rss", version="2.0")
        rss.set("xmlns:itunes", ITUNES_NS)
        channel = ET.SubElement(rss, "channel")
        ET.SubElement(channel, "title").text = "SuperCow AI News Podcast"
        ET.SubElement(channel, "link").text = "https://mommocmoc.github.io/supercow-ai-news-podcast"
        ET.SubElement(channel, "description").text = "Daily AI news generated by SuperCow Agent using NotebookLM and Goose"
        ET.SubElement(channel, "language").text = "ko-KR"
        
        ET.SubElement(channel, "{%s}author" % ITUNES_NS).text = "Super Cow 소재환"
        ET.SubElement(channel, "{%s}explicit" % ITUNES_NS).text = "false"
        ET.SubElement(channel, "{%s}category" % ITUNES_NS, text="Technology")
        itunes_owner = ET.SubElement(channel, "{%s}owner" % ITUNES_NS)
        ET.SubElement(itunes_owner, "{%s}name" % ITUNES_NS).text = "소재환"
        ET.SubElement(itunes_owner, "{%s}email" % ITUNES_NS).text = "hey@cowcowwow.kr"
        
        # Add podcast cover image
        itunes_image = ET.SubElement(channel, "{%s}image" % ITUNES_NS)
        itunes_image.set("href", image_url)
    else:
        tree = ET.parse(feed_file)
        rss = tree.getroot()
        channel = rss.find("channel")
        
        # Ensure itunes:image exists at channel level
        it_image = channel.find("{%s}image" % ITUNES_NS)
        if it_image is None:
            it_image = ET.SubElement(channel, "{%s}image" % ITUNES_NS)
        it_image.set("href", image_url)

    # Add new episode
    item = ET.SubElement(channel, "item")
    ET.SubElement(item, "title").text = title
    
    file_path = os.path.join("audio", audio_filename)
    file_size = os.path.getsize(file_path) if os.path.exists(file_path) else 0
    
    # Use KST (UTC+9) for pubDate
    kst = timezone(timedelta(hours=9))
    now_kst = datetime.now(kst)
    
    mime_type = "audio/x-m4a" if audio_filename.lower().endswith(".m4a") else "audio/mpeg"
    ET.SubElement(item, "enclosure", url=audio_url, type=mime_type, length=str(file_size))
    ET.SubElement(item, "pubDate").text = now_kst.strftime("%a, %d %b %Y %H:%M:%S +0900")
    ET.SubElement(item, "description").text = description
    ET.SubElement(item, "{%s}summary" % ITUNES_NS).text = description
    ET.SubElement(item, "guid", isPermaLink="false").text = audio_url
    ET.SubElement(item, "{%s}explicit" % ITUNES_NS).text = "false"

    # Save fixed XML
    xml_str = ET.tostring(rss, encoding="utf-8").decode("utf-8")
    if xml_str.count("xmlns:itunes") > 1:
        rss.attrib.pop("xmlns:itunes", None)
        xml_str = ET.tostring(rss, encoding="utf-8").decode("utf-8")

    with open(feed_file, "w", encoding="utf-8") as f:
        f.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n")
        f.write(xml_str)
        
    print(f"Updated {feed_file} with cover and episode {audio_filename} in KST")

if __name__ == "__main__":
    if len(sys.argv) < 4:
        print("Usage: python update_feed.py <title> <audio_filename> <description>")
    else:
        update_podcast_feed(sys.argv[1], sys.argv[2], sys.argv[3])
